#!/usr/bin/env python3
"""
Slidev PPT 生成脚本
将长文本自动转换为 Slidev Markdown 格式

用法:
    python generate_slides.py "你的文章内容"
    python generate_slides.py --file article.txt
    python generate_slides.py --file article.txt --output slides.md
"""

import sys
import os
import re
import argparse


def extract_title(content):
    """从内容中提取标题（通常是第一行或第一段）"""
    lines = content.strip().split('\n')
    
    # 尝试找第一行非空行
    for line in lines:
        line = line.strip()
        if line and len(line) < 100:
            return line
    
    return "演示文稿"


def split_into_sections(content):
    """将内容拆分为多个章节"""
    # 按常见分隔符拆分
    # 支持：## 标题、数字+点+标题、换行换行
    
    sections = []
    
    # 首先尝试按 markdown 标题拆分
    pattern = r'(?:^|\n)(#{1,3}\s+.+?)(?=\n#{1,3}\s|\Z)'
    matches = list(re.finditer(pattern, content, re.DOTALL))
    
    if len(matches) >= 2:
        # 使用 markdown 标题作为分割
        for match in matches:
            section = match.group(1).strip()
            if section:
                sections.append(section)
    else:
        # 按段落拆分
        paragraphs = [p.strip() for p in content.split('\n\n') if p.strip()]
        
        # 合并短段落，形成合理长度的页面
        current_section = []
        for p in paragraphs:
            current_section.append(p)
            # 如果段落够长或包含句号（完整句子），结束当前section
            if len(p) > 100 or p.endswith('。') or p.endswith('.'):
                sections.append('\n\n'.join(current_section))
                current_section = []
        
        if current_section:
            sections.append('\n\n'.join(current_section))
    
    return sections


def format_bullets(text):
    """将文本转换为 bullet points"""
    lines = text.split('\n')
    bullets = []
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
        
        # 移除 markdown 标记
        line = re.sub(r'^#{1,3}\s*', '', line)  # 移除标题标记
        line = re.sub(r'^[-*+]?\s*', '', line)  # 移除已有列表标记
        
        if line and len(line) > 5:  # 过滤太短的行
            bullets.append(line)
    
    return bullets


def generate_slidev_markdown(title, sections, theme="seriph"):
    """生成 Slidev Markdown 内容"""
    
    lines = []
    
    # Frontmatter
    lines.extend([
        "---",
        f'theme: {theme}',
        "background: https://source.unsplash.com/collection/9473456/1920x1080",
        "class: text-center",
        "highlighter: shiki",
        "lineNumbers: true",
        "info: |",
        f"  ## {title}",
        "  Generated by Slidev PPT Generator",
        "drawings:",
        "  persist: false",
        "transition: slide-left",
        f"title: {title}",
        "---\n"
    ])
    
    # 标题页
    lines.extend([
        f"# {title}",
        "",
        "Generated with ❤️ by AI Assistant",
        "",
        "<!-- 演讲者备注：这是开场白 -->\n"
    ])
    
    # 目录页（如果章节足够多）
    if len(sections) > 3:
        lines.extend([
            "---",
            "layout: center",
            "class: text-center",
            "---\n",
            "# 目录",
            "",
        ])
        for i, section in enumerate(sections[:6], 1):  # 最多显示6个
            # 提取章节标题（第一行或前30个字符）
            section_title = section.split('\n')[0][:30]
            lines.append(f"{i}. {section_title}")
        lines.append("\n")
    
    # 内容页
    for i, section in enumerate(sections, 1):
        lines.append("---")
        lines.append("layout: default")
        lines.append("---\n")
        
        # 提取章节标题
        section_lines = section.split('\n')
        raw_title = section_lines[0].strip()
        
        # 清理标题中的 markdown 标记
        clean_title = re.sub(r'^#{1,3}\s*', '', raw_title)
        if not clean_title or len(clean_title) < 3:
            clean_title = f"第 {i} 部分"
        
        lines.append(f"# {clean_title}")
        lines.append("")
        
        # 剩余内容转为 bullet points
        remaining_text = '\n'.join(section_lines[1:])
        bullets = format_bullets(remaining_text)
        
        if bullets:
            for bullet in bullets[:6]:  # 每页最多6个 bullet
                lines.append(f"- {bullet}")
        else:
            # 如果没有提取到 bullets，显示摘要
            summary = remaining_text[:200] + "..." if len(remaining_text) > 200 else remaining_text
            lines.append(summary)
        
        lines.append("")
        lines.append(f"<!-- 演讲者备注：{clean_title} 的补充说明 -->\n")
    
    # 结束页
    lines.extend([
        "---",
        "layout: center",
        "class: text-center",
        "---\n",
        "# 感谢观看",
        "",
        "欢迎提问与交流 👋",
        "",
        "<!-- 演讲者备注：结束语，邀请互动 -->\n"
    ])
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description='将文本转换为 Slidev Markdown')
    parser.add_argument('content', nargs='?', help='文章内容（直接输入）')
    parser.add_argument('--file', '-f', help='从文件读取文章内容')
    parser.add_argument('--output', '-o', default='slides.md', help='输出文件路径（默认：slides.md）')
    parser.add_argument('--theme', '-t', default='seriph', help='Slidev 主题（默认：seriph）')
    
    args = parser.parse_args()
    
    # 获取内容
    if args.file:
        if not os.path.exists(args.file):
            print(f"❌ 错误：文件不存在 - {args.file}")
            sys.exit(1)
        with open(args.file, 'r', encoding='utf-8') as f:
            content = f.read()
    elif args.content:
        content = args.content
    else:
        # 尝试从标准输入读取
        content = sys.stdin.read()
        if not content.strip():
            print("❌ 错误：未提供文章内容")
            print("用法：")
            print("  python generate_slides.py '你的文章内容'")
            print("  python generate_slides.py --file article.txt")
            print("  echo '文章内容' | python generate_slides.py")
            sys.exit(1)
    
    # 提取标题
    title = extract_title(content)
    
    # 拆分为章节
    sections = split_into_sections(content)
    
    print(f"📄 标题：{title}")
    print(f"📑 章节数：{len(sections)}")
    print(f"🎨 主题：{args.theme}")
    
    # 生成 Slidev Markdown
    markdown = generate_slidev_markdown(title, sections, args.theme)
    
    # 写入文件
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(markdown)
    
    print(f"✅ 已生成：{args.output}")
    print(f"🚀 运行 'npm run dev' 预览演示文稿")


if __name__ == '__main__':
    main()
